Restore KHR_lights_punctual in glTF Exporter
SergioRZMasson/Babylon.js pull request #1
Opened 2024-10-28 19:44 UTC by alexchuber

Restored the commented-out extension and added a quick visualization test to compare import and export of a sample directional light glb.

2024-10-29 17:52 UTC, SergioRZMasson requested changes
We probably need to handle handiness when managing the light transforms the same way we do in the nodes transforms. We might need to change  postExportNodeAsync function contract to receive a handiness boolean.

2024-10-29 17:52 UTC, SergioRZMasson commented on packages/dev/serializers/src/glTF/2.0/Extensions/KHR_lights_punctual.ts
> +                            const parentTranslation = Vector3.FromArrayToRef(parentNode.translation || [0, 0, 0], 0, TmpVectors.Vector3[0]);
@alexchuber , I wonder if we need to change this code to handle the new conversion between left and right handed systems. Try exporting this using useRightHandedSystem = true

2024-11-04 17:54 UTC, alexchuber commented on packages/dev/serializers/src/glTF/2.0/Extensions/KHR_lights_punctual.ts
> +                            const parentTranslation = Vector3.FromArrayToRef(parentNode.translation || [0, 0, 0], 0, TmpVectors.Vector3[0]);
Totally forgot about handiness updates!

We actually don't need to worry about the parentNode's handiness-- by the time it reaches here, the parentNode's transformations will have already been set in the correct RH system. 

But we do need to worry about the light node's handiness. This extension-specific code is responsible for setting the light node's transformations, and it looks like it was already wrong before. It should be fixed now + able to accomodate both hand systems.

2024-11-04 17:56 UTC, alexchuber commented on packages/dev/serializers/src/glTF/2.0/Extensions/KHR_lights_punctual.ts
> +                            const parentTranslation = Vector3.FromArrayToRef(parentNode.translation || [0, 0, 0], 0, TmpVectors.Vector3[0]);
(If the parentNode's transformations haven't been set by this time anyway, then it wouldn't be in the _nodes list, since the parentNode is a TransformNode and TransformNodes have their translation/scale/rotation set before being added to the _nodes list)

2024-11-12 15:18 UTC, SergioRZMasson approved these changes

2024-11-12 15:18 UTC, merged